name: Update README

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Count LeetCode Solutions
        run: |
          TOTAL=$(find . -name "*.cpp" | wc -l)
          echo "TOTAL=$TOTAL" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s/<!--TOTAL-->.*<!--TOTAL-->/<!--TOTAL-->$TOTAL<!--TOTAL-->/" README.md

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add README.md

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Update README progress"
            git push
          fi
